# RAGFlow集成配置示例
# 用于配置RAGFlow使用企业知识库的API

api_endpoints:
  # 企业知识库检索API
  kb_retriever:
    url: http://localhost:8000/api/v1/ragflow/retrieve
    method: POST
    headers:
      Content-Type: application/json
      # 如果API需要认证，可以添加
      # Authorization: Bearer ${KB_API_KEY}
    
    # 请求模板
    request_template:
      query: "{{query}}"  # 从RAGFlow接收的查询
      top_k: 5            # 返回结果数量
      datasources: null   # 可以指定特定数据源，如 ["primary", "custom"]
      filters: null       # 可以添加过滤条件，如 {"file_type": "pdf"}
    
    # 响应处理
    response_mapping:
      context_key: "contexts"       # 返回的上下文数组字段
      context_content_key: "content"  # 上下文内容字段
      context_metadata_key: "metadata"  # 上下文元数据字段

# RAGFlow链配置
rag_flow:
  retriever:
    type: api
    config:
      api_endpoint: kb_retriever
      timeout: 30  # 超时时间（秒）
      
  llm:
    type: openai
    config:
      model: gpt-4-turbo
      temperature: 0.7
      max_tokens: 1000
      
  prompt_template: |
    你是一个企业知识库助手。请使用下面提供的上下文来回答用户的问题。
    如果无法从上下文中找到答案，请说明你不知道，不要编造信息。
    
    上下文:
    {{contexts}}
    
    用户问题: {{query}}
    
    请提供详细且有帮助的回答:

# 部署配置
deployment:
  environment: development  # development, staging, production
  logging:
    level: INFO
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API服务配置
api:
  host: 0.0.0.0
  port: 8050
  debug: true
  cors:
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"] 